# Generated by Django 6.1.1 on 2026-10-05 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_business_review_business_business_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.TextField(help_text='How can we confirm you own this business?')),
                ('contact_phone', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='business',
            name='booking_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='business',
            name='price_range',
            field=models.CharField(blank=True, choices=[('$', 'Budget'), ('$$', 'Mid-range'), ('$$$', 'Premium')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed')], default='unclaimed', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='listings.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='services',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='listings_bu_status_aef7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_verified'], name='listings_bu_is_veri_74ab37_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category', 'status'], name='listings_bu_categor_91abd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('source', 'external_id'), name='uniq_business_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='uniq_review_per_user_per_business'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='listings.business'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['business', 'state'], name='listings_cl_busines_e3f2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['claimant', 'state'], name='listings_cl_claiman_fd1ae8_idx'),
        ),
        migrations.AddConstraint(
            model_name='claimrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('business', 'claimant'), name='one_pending_claim_per_user_per_business'),
        ),
    ]
